name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Say hello to Sarvani
        run: echo "Hi Sarvani.."
